name: tokyo_marine_insurance
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_modular: ^5.0.3
  dio: ^5.8.0+1
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.7
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0
  webview_flutter_web: ^0.2.2+4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.2
  bloc_test: ^10.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/client_logo/
    - assets/images/icon_appbar/
    - assets/images/icon_person/
    - assets/images/social_media/