// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-yqL6jjVG7OddJaICT8Ga_5O05ZB2_Jg',
    appId: '1:418767284399:web:f5bd7a02138adfe1664c5a',
    messagingSenderId: '418767284399',
    projectId: 'tokyomarineinsurance-51ab4',
    authDomain: 'tokyomarineinsurance-51ab4.firebaseapp.com',
    storageBucket: 'tokyomarineinsurance-51ab4.firebasestorage.app',
    measurementId: 'G-5LXR2KFEMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPSQ4FZncNNQGAsyB5vxK9zaZdcDa0Gn4',
    appId: '1:418767284399:android:ed8423564b2f2d9a664c5a',
    messagingSenderId: '418767284399',
    projectId: 'tokyomarineinsurance-51ab4',
    storageBucket: 'tokyomarineinsurance-51ab4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoqcQy6V37bYk2B4QMOFGqUFqDmqvuuPY',
    appId: '1:418767284399:ios:9ff8810b237b1e5f664c5a',
    messagingSenderId: '418767284399',
    projectId: 'tokyomarineinsurance-51ab4',
    storageBucket: 'tokyomarineinsurance-51ab4.firebasestorage.app',
    iosBundleId: 'br.com.tokyo.tokyoMarineInsurance',
  );
}
